-- CreateTable
CREATE TABLE "Cell" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "occupied" BOOLEAN NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "gridId" INTEGER NOT NULL,
    CONSTRAINT "Cell_gridId_fkey" FOREIGN KEY ("gridId") REFERENCES "Grid" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
